version: '3.9'
services:
  postgres:
    container_name: Postgres
    image: postgres
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: